### ISSUE TITLE
Wrong title property

### ISSUE THREAD

**Issue by markparolisi** [bufferapp/buffer-chrome#18]
When scraping pages I'm getting the meta title instead of the og:title.
I found this method in the shared library: https://github.com/bufferapp/buffer-extension-shared/blob/60fb065f6e81e1aeff8e657cb158f1f58ae3f9bc/embeds/buffer-scraper.js#L176

**Comment by cenderin** [comment]
$('meta[property="og:title"]').prop('content') || document.title || $('h1').first().text() || ''

The operator is an OR aka ||.  So this statement is pretty much saying og:title OR the meta title OR the text of the first h1 property on the page OR an empty string.  If there is a page that has an og:title and it's skipping over that I would post the url for that page.  Otherwise I don't think this is an issue the way you describe it since it's doing exactly how its programmed.  

Thanks :+1:

**Comment by djfarrelly** [comment]
Hey @markparolisi, @cenderin - the scraper included in the shared repo is not currently being used. This is the logic for grabbing the title of the page for use as the main text to share: https://github.com/bufferapp/buffer-extension-shared/blob/c0b4119e02ea2bc589ee6cf9816f17bde89a31a5/buffer-overlay.js#L269-L286

It still should return the `og:title` if it's correctly formatted :smile:

**Comment by cenderin** [comment]
I see, well that one looks kinda similar, if it doesn't have og:title then
it uses the document.title.  So I guess just make sure you have og:title
and it will use it!
